language: go
go:
  - 1.x
  - master
install:
  - go get -u github.com/golang/lint/golint
before_script:
  - if [[ -n "$(go fmt ./...)" ]]; then exit 1; fi
  - golint -set_exit_status $(go list ./...)
  - go vet ./...
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
